#cloud-config
users:
  - name: ang
    primary_group: ang
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDG1fLJ/LikdBBcMFJlJbb3FH+yXJORx72GCl3bXTUYN ang # change with your yml/yaml file

packages:
  - ripgrep
  - rsync
  - neovim
  - fd
  - less
  - man-db
  - bash-completion
  - tmux

disable_root: true